import type { RelicKind } from '../lib/relicGeometry.ts';
import type { SpectralKey } from './types.ts';

/**
 * The Archive: objects reconstructed from the Serein Signal. The Ithra did
 * not send things — they sent descriptions of things, in light, and the
 * Institute rebuilds them as holographic reconstructions. "Integrity" is the
 * fraction of the object's description that survived the crossing.
 */
export interface Relic {
  id: string;
  catalog: string;
  name: string;
  /** Their word for it, rendered in Ithran script. */
  ithran: string;
  era: string;
  kind: RelicKind;
  line: SpectralKey;
  integrity: number;
  material: string;
  dimensions: string;
  received: string;
  summary: string;
  description: readonly string[];
  notes: string;
  related: readonly string[];
  seed: number;
}

export const relics: readonly Relic[] = [
  {
    id: 'sr-0004',
    catalog: 'SR-0004',
    name: 'The Ennet Spiral',
    ithran: 'enet',
    era: 'tidal-age',
    kind: 'seed',
    line: 'o3',
    integrity: 71,
    material: 'Mineralised colony shell, luminous inclusions',
    dimensions: '9.4 × 6.1 cm',
    received: 'OST 2244.02.19 · Dish 31',
    summary: 'A fossil colony that grew in a golden spiral — and recorded the tides in its rings.',
    description: [
      'Long before there were Ithra, the shallows of Ennet were crowded with colonies of light-making cells that grew their shells outward in a perfect phyllotactic spiral. Each ring of the spiral corresponds to a single tide.',
      'The Ithra kept this one for three million turns. They called it the first book, because it had been written by the sea about itself, one night at a time.',
    ],
    notes:
      'Ring spacing decodes as a beat pattern of two tidal periods (4.1 h and 6.3 h), consistent with the two moons of Ithris. 29% of the outer whorl is lost to signal fade.',
    related: ['sr-0009', 'sr-0086'],
    seed: 4,
  },
  {
    id: 'sr-0009',
    catalog: 'SR-0009',
    name: 'Pulse Stone of the Shallows',
    ithran: 'hael',
    era: 'tidal-age',
    kind: 'tablet',
    line: 'o3',
    integrity: 54,
    material: 'Basalt, scored',
    dimensions: '22 × 17 × 3 cm',
    received: 'OST 2247.11.30 · Dish 08',
    summary: 'Not writing — a tally of flashes, scratched by something that could count.',
    description: [
      'The marks on this stone are long and short strokes in rows, like a clumsy score. The Institute spent eleven years assuming they were decoration.',
      'They are counts. Someone — possibly not yet an Ithra — watched a light flash in the dark and scratched one stroke for every pulse, and a longer stroke for every pause. It is the oldest known transcription of their language.',
    ],
    notes:
      'Stroke lengths cluster in two populations (ratio 1 : 3.2). Mapping short = pulse, long = rest yields a repeating 41-symbol sequence also present in SR-0021.',
    related: ['sr-0004', 'sr-0021', 'sr-0073'],
    seed: 9,
  },
  {
    id: 'sr-0013',
    catalog: 'SR-0013',
    name: 'Brine Lens',
    ithran: 'soru',
    era: 'tidal-age',
    kind: 'lens',
    line: 'o3',
    integrity: 88,
    material: 'Salt crystal, tide-polished',
    dimensions: '⌀ 6.8 cm',
    received: 'OST 2238.06.04 · Dish 44',
    summary: 'A natural lens of crystallised brine, turned smooth by a million tides.',
    description: [
      'Salt crystals the size of a palm formed in the drying pools of the Ennet flats, and the tides rolled them for so long that some became almost perfect lenses.',
      'The early Ithra discovered that a lens could gather the faint glow of another colony and make it bright. The signal describes this one being passed hand to hand at gatherings, so that everyone could see a light that was far away.',
    ],
    notes:
      'High integrity: the description was repeated in 14 separate places in the stream. Focal length reconstructed at 11.2 cm.',
    related: ['sr-0097', 'sr-0128'],
    seed: 13,
  },
  {
    id: 'sr-0021',
    catalog: 'SR-0021',
    name: 'The Lantern of Ossa Who Waits',
    ithran: 'ossa',
    era: 'age-of-lanterns',
    kind: 'lantern',
    line: 'na',
    integrity: 93,
    material: 'Brine-glass, bone lattice, living culture (lost)',
    dimensions: '31 × 14 cm',
    received: 'OST 2239.03.14 · Dish 17',
    summary: 'The oldest named thing in the archive: a lantern that waited for someone for sixty years.',
    description: [
      'Ossa Who Waits was a household lantern in a fishing town on the Senn Reach. Her keeper taught her a single sequence — come home — and went to sea.',
      'The keeper did not come back. Ossa repeated her sequence every night for sixty-one turns, until she died. The town kept her glass, and her story, and fifty-eight thousand years later they put both into the signal.',
    ],
    notes:
      'The sequence “come home” (7 pulses, 2 rests, 3 pulses) is the most repeated phrase in the entire stream after the carrier itself.',
    related: ['sr-0027', 'sr-0038', 'sr-0116'],
    seed: 21,
  },
  {
    id: 'sr-0027',
    catalog: 'SR-0027',
    name: 'Keeper’s Vessel',
    ithran: 'mira',
    era: 'age-of-lanterns',
    kind: 'vessel',
    line: 'na',
    integrity: 77,
    material: 'Glazed clay, sugar residue',
    dimensions: '26 × 18 cm',
    received: 'OST 2241.09.08 · Dish 52',
    summary: 'A feeding jar for lanterns: brine in the belly, sugar in the neck.',
    description: [
      'A lantern had to be fed, and this is what it was fed from: a two-chambered vessel, brine below and sugar syrup above, with a slow wick of fibre that let the lantern drink through the night.',
      'The shape recurs across the whole Age of Lanterns with almost no change. The Ithra considered it finished. They did not improve things that were already kind.',
    ],
    notes:
      'Profile reconstructed from three partial descriptions and one poem. Neck proportion uncertain (±8%).',
    related: ['sr-0021', 'sr-0103'],
    seed: 27,
  },
  {
    id: 'sr-0033',
    catalog: 'SR-0033',
    name: 'Crystal of the Night Market',
    ithran: 'tessa',
    era: 'age-of-lanterns',
    kind: 'lattice',
    line: 'na',
    integrity: 62,
    material: 'Quartz, sealed light-sequence',
    dimensions: '7 × 7 × 5 cm',
    received: 'OST 2250.12.01 · Dish 03',
    summary: 'A quartz that kept a light-sequence for ever: the prices at a market, one night.',
    description: [
      'The first things the Ithra sealed into crystal were not poems or laws. They were prices. This crystal holds the sequence a market-keeper flashed at the entrance of a night market: what fish cost, what rope cost, which stalls were open.',
      'Scholars at the Institute find it the most moving object in the archive, for exactly that reason.',
    ],
    notes:
      'Lattice spacing and inclusion pattern both encode data; only the inclusion layer was transmitted in full.',
    related: ['sr-0052', 'sr-0009'],
    seed: 33,
  },
  {
    id: 'sr-0038',
    catalog: 'SR-0038',
    name: 'Lamplighter’s Ring',
    ithran: 'senn',
    era: 'age-of-lanterns',
    kind: 'ring',
    line: 'na',
    integrity: 84,
    material: 'Bronze-analogue alloy, engraved',
    dimensions: '⌀ 3.9 cm',
    received: 'OST 2243.05.27 · Dish 19',
    summary: 'The guild ring of the lamplighters of Senn Reach, engraved with the guild’s oath.',
    description: [
      'The lamplighters tended the public lanterns of the Senn Reach for two thousand turns, and their records survive almost whole. Each member wore a ring engraved with the guild’s oath in pulse-script.',
      'The oath reads, approximately: no window dark that wants to be lit.',
    ],
    notes:
      'Engraving decoded directly from the transmitted surface map. See Transmission: “The Lamplighters”.',
    related: ['sr-0021', 'sr-0116'],
    seed: 38,
  },
  {
    id: 'sr-0044',
    catalog: 'SR-0044',
    name: 'The Singing Stone',
    ithran: 'aurel',
    era: 'the-resonance',
    kind: 'bell',
    line: 'hb',
    integrity: 69,
    material: 'Tuned crystal',
    dimensions: '40 × 32 cm',
    received: 'OST 2246.08.15 · Dish 61',
    summary:
      'The first deliberate resonant record: a crystal that held a lantern’s pattern for eleven turns.',
    description: [
      'Shaped like a bell and tuned by hand, the Singing Stone was struck while a lantern shone through it. For eleven turns afterward it rang with the lantern’s pattern folded into its note.',
      'It is the founding object of the Resonance, and the Ithra kept it in the first chamber of the Mereth Libraries until the libraries themselves were read into the Choir.',
    ],
    notes:
      'The strike frequency (in their units) implies a resonant mode we reproduce in the Resonance instrument as mode (5, 3).',
    related: ['sr-0052', 'sr-0057', 'sr-0140'],
    seed: 44,
  },
  {
    id: 'sr-0052',
    catalog: 'SR-0052',
    name: 'Mereth Library Key',
    ithran: 'meret',
    era: 'the-resonance',
    kind: 'lattice',
    line: 'hb',
    integrity: 58,
    material: 'Ice-stable crystal',
    dimensions: '14 × 9 × 9 cm',
    received: 'OST 2252.04.02 · Dish 12',
    summary: 'A tuning key: struck at the door of a library chamber, it told the walls what to remember.',
    description: [
      'The Resonant Libraries of Mereth were caverns of tuned crystal kept still by the cold. To add to a chamber, a librarian struck its key at the threshold; the key’s lattice set the whole chamber ringing in a pattern ready to receive.',
      'Each chamber had one key. This one opened the chamber of weather.',
    ],
    notes:
      'Hexagonal lattice, 4 shells. The chamber it keyed is described elsewhere in 1,210 fragments, all about rain.',
    related: ['sr-0044', 'sr-0061', 'sr-0033'],
    seed: 52,
  },
  {
    id: 'sr-0057',
    catalog: 'SR-0057',
    name: 'Resonance Plate',
    ithran: 'chlad',
    era: 'the-resonance',
    kind: 'lens',
    line: 'hb',
    integrity: 81,
    material: 'Glass plate, fixed mineral dust',
    dimensions: '⌀ 38 cm',
    received: 'OST 2240.10.21 · Dish 27',
    summary: 'Sand that settled on a singing plate, fixed in place: a standing wave made visible.',
    description: [
      'Scatter fine dust on a plate and make it sing, and the dust gathers on the places that do not move. The Ithra used plates like this to see the shape of a sound before they trusted a crystal with it.',
      'This one was fixed with a glaze at the moment the dust settled, and kept as a teaching object. The pattern is still perfectly symmetric after thirty-six thousand years in transit.',
    ],
    notes: 'The frozen figure matches a square-plate mode — explore it in the Resonance instrument.',
    related: ['sr-0044', 'sr-0013'],
    seed: 57,
  },
  {
    id: 'sr-0061',
    catalog: 'SR-0061',
    name: 'Tuning Spire of Mereth',
    ithran: 'veil',
    era: 'the-resonance',
    kind: 'spire',
    line: 'hb',
    integrity: 46,
    material: 'Crystal column, ice-cut',
    dimensions: '2.1 m',
    received: 'OST 2255.01.09 · Dish 40',
    summary: 'One of the thousand spires that kept the libraries in tune through the long cold.',
    description: [
      'Ice shifts, and a shifting library forgets. The Ithra ringed each library chamber with tall spires of crystal that sang a steady reference note, so the walls could correct themselves as the ice moved.',
      'Most spires are described only by their notes. This is one of the few whose shape was sent as well.',
    ],
    notes: 'Low integrity: the upper third is extrapolated from spire-standards in the Resonant Codex.',
    related: ['sr-0052', 'sr-0044'],
    seed: 61,
  },
  {
    id: 'sr-0068',
    catalog: 'SR-0068',
    name: 'The Dimmed Lantern',
    ithran: 'nuit',
    era: 'quiet-schism',
    kind: 'lantern',
    line: 'he',
    integrity: 66,
    material: 'Brine-glass, lacquered shutter',
    dimensions: '29 × 15 cm',
    received: 'OST 2249.06.30 · Dish 22',
    summary: 'A lantern half-shuttered on one side — lit for your own shore, dark to the other.',
    description: [
      'During the Quiet Schism the Ithra did not fight. They dimmed. Lanterns were fitted with shutters that hid their light from the opposite shore, so that for six thousand turns whole coastlines went dark to each other.',
      'This lantern’s shutter is painted on the inside with the far shore as it looked when it was last lit — a memory kept facing inward.',
    ],
    notes:
      'The shutter painting was transmitted as a separate image, 40% intact. The lantern itself is nearly whole.',
    related: ['sr-0073', 'sr-0079', 'sr-0021'],
    seed: 68,
  },
  {
    id: 'sr-0073',
    catalog: 'SR-0073',
    name: 'The Accord of Dusk',
    ithran: 'dusk',
    era: 'quiet-schism',
    kind: 'tablet',
    line: 'he',
    integrity: 97,
    material: 'Glass tablet, twin-inscribed',
    dimensions: '48 × 36 × 4 cm',
    received: 'OST 2237.12.24 · Dish 01',
    summary: 'The treaty that ended the Schism: memory may be kept, but only if freely given.',
    description: [
      'The Accord is short. Memory may be kept. Memory must be given, never taken. Any memory may be asked back, and must then be released. It was inscribed twice on the same tablet, once by each side, in their two styles of pulse-script.',
      'Every later part of the signal obeys it. When the Institute finds a hole in the stream that is too clean to be damage, it is usually an Ithra, long ago, asking for their memory back.',
    ],
    notes:
      'The most complete object in the archive; its text is embedded, redundantly, in every transmission cycle.',
    related: ['sr-0068', 'sr-0079', 'sr-0134'],
    seed: 73,
  },
  {
    id: 'sr-0079',
    catalog: 'SR-0079',
    name: 'Mask of the Unlit Generation',
    ithran: 'unlit',
    era: 'quiet-schism',
    kind: 'mask',
    line: 'he',
    integrity: 52,
    material: 'Pressed fibre, pigment',
    dimensions: '24 × 17 cm',
    received: 'OST 2253.03.03 · Dish 36',
    summary: 'Worn by children born during the Schism, who had never seen the far shore lit.',
    description: [
      'Seventeen hundred turns into the Schism, a generation came of age that had never seen the opposite coast illuminated. Their elders made them masks with no eye-holes, only small perforations, so that the children would learn to see by pinpricks of light.',
      'When the Accord was signed and both shores lit in a single night, the masks were taken off together.',
    ],
    notes: 'The perforation pattern is a star chart of the southern sky of Ithris.',
    related: ['sr-0073', 'sr-0068'],
    seed: 79,
  },
  {
    id: 'sr-0086',
    catalog: 'SR-0086',
    name: 'Ring-Garden Seed',
    ithran: 'solen',
    era: 'long-noon',
    kind: 'seed',
    line: 'mg',
    integrity: 74,
    material: 'Seed husk, luminous',
    dimensions: '5.2 × 3.4 cm',
    received: 'OST 2248.07.07 · Dish 58',
    summary: 'A seed from the gardens that floated in the rings of Sollen.',
    description: [
      'In the Long Noon a fifth of all Ithra lived in gardens seeded into the rings of the giant Sollen. The plants there grew in spirals, in low gravity, toward a sun they saw every six hours.',
      'This seed is from a flowering vine that was bred to glow faintly at night, so that the gardens could be seen from Ithris as a thin bright thread across the sky.',
    ],
    notes:
      'Phyllotaxis identical to SR-0004: the Ithra deliberately bred the garden plants to echo the tidal colonies.',
    related: ['sr-0004', 'sr-0103'],
    seed: 86,
  },
  {
    id: 'sr-0092',
    catalog: 'SR-0092',
    name: 'Atlas of Near Stars',
    ithran: 'atlas',
    era: 'long-noon',
    kind: 'map',
    line: 'mg',
    integrity: 89,
    material: 'Engraved glass sphere',
    dimensions: '⌀ 52 cm',
    received: 'OST 2242.04.18 · Dish 09',
    summary: 'Every star within four hundred light-years, and not one of them answering.',
    description: [
      'The observatories on Carrow charted 11,406 stars and listened to every one for a sign of anyone else speaking in light. The results were engraved on a glass sphere, each star a tiny cut that catches the light.',
      'There is no mark on the sphere for a reply. The Ithra added a line of text around the equator instead: we will be the ones who answered.',
    ],
    notes:
      'Cross-matching the atlas with our own catalogues places Vael 36,200 ± 400 light-years away, behind the Cygnus Rift.',
    related: ['sr-0097', 'sr-0121'],
    seed: 92,
  },
  {
    id: 'sr-0097',
    catalog: 'SR-0097',
    name: 'Carrow Telescope Mirror',
    ithran: 'carow',
    era: 'long-noon',
    kind: 'lens',
    line: 'mg',
    integrity: 63,
    material: 'Silvered glass segment',
    dimensions: '⌀ 1.8 m',
    received: 'OST 2251.08.11 · Dish 47',
    summary: 'A segment from the light-telescopes of Carrow, the world that always faced its star.',
    description: [
      'Carrow was tidally locked: one face burned, the other froze, and a band of permanent twilight ran between them. On that band the Ithra built their great telescopes, where the ground never moved and the sky never changed.',
      'This mirror segment was part of the largest of them. When Vael swelled and Carrow was engulfed, the mirror was still pointing outward.',
    ],
    notes:
      'Figure and coating reconstructed; the grinding pattern carries a maker’s mark in pulse-script: “for seeing further”.',
    related: ['sr-0092', 'sr-0013', 'sr-0110'],
    seed: 97,
  },
  {
    id: 'sr-0103',
    catalog: 'SR-0103',
    name: 'Garden Vessel of Sollen',
    ithran: 'sola',
    era: 'long-noon',
    kind: 'vessel',
    line: 'mg',
    integrity: 80,
    material: 'Spun ring-ice ceramic',
    dimensions: '34 × 22 cm',
    received: 'OST 2245.01.26 · Dish 55',
    summary: 'A water jar spun in low gravity, impossibly thin, from the ring gardens.',
    description: [
      'In the ring gardens, potters spun their vessels in near-weightlessness, which let them draw the walls thinner than any Ithris potter could. This jar is almost translucent.',
      'It carried water between the garden terraces. Its shape is the Keeper’s Vessel of the Age of Lanterns, stretched by a world with almost no gravity.',
    ],
    notes:
      'Wall thickness transmitted as 0.4 mm. The Institute’s ceramicists have not been able to reproduce it.',
    related: ['sr-0027', 'sr-0086'],
    seed: 103,
  },
  {
    id: 'sr-0110',
    catalog: 'SR-0110',
    name: 'Red Dawn Record',
    ithran: 'vael',
    era: 'the-reddening',
    kind: 'instrument',
    line: 'ha',
    integrity: 72,
    material: 'Gimballed spectroscope, brass-analogue',
    dimensions: '62 × 62 × 70 cm',
    received: 'OST 2247.03.03 · Dish 14',
    summary: 'The instrument that first saw Vael change colour. Its record is calm.',
    description: [
      'Astronomers on Carrow kept this spectroscope trained on Vael for four hundred turns as a matter of routine. In 3,200 BE its readings began to drift toward the red.',
      'The entry that records the change is short and exact, and it ends with a line the Institute has never quite been able to translate. The closest reading is: well. Now we know.',
    ],
    notes:
      'Gimbal geometry fully transmitted. The drift it recorded matches a star leaving the main sequence.',
    related: ['sr-0097', 'sr-0121'],
    seed: 110,
  },
  {
    id: 'sr-0116',
    catalog: 'SR-0116',
    name: 'Last Lantern of Senn Reach',
    ithran: 'last',
    era: 'the-reddening',
    kind: 'lantern',
    line: 'ha',
    integrity: 90,
    material: 'Brine-glass, travel cage',
    dimensions: '33 × 16 cm',
    received: 'OST 2240.01.01 · Dish 17',
    summary: 'Carried offworld as the tidal seas boiled away. It was still lit.',
    description: [
      'When the seas of Ithris began to boil, the last lamplighters of Senn Reach took down the public lanterns one by one and carried them up to the ships. This was the last.',
      'It travelled to Sollen, then to Mereth, then to Ennis, and it was read into the Choir with its keeper. The signal says it was still lit.',
    ],
    notes:
      'Received on the same dish, same date-of-year, as SR-0021 — the Institute keeps the two side by side.',
    related: ['sr-0021', 'sr-0038', 'sr-0140'],
    seed: 116,
  },
  {
    id: 'sr-0121',
    catalog: 'SR-0121',
    name: 'Evacuation Map of Ithris',
    ithran: 'ithris',
    era: 'the-reddening',
    kind: 'map',
    line: 'ha',
    integrity: 67,
    material: 'Glass sphere, route-etched',
    dimensions: '⌀ 44 cm',
    received: 'OST 2254.06.12 · Dish 29',
    summary: 'The homeworld, and every route off it, as the seas rose into the sky.',
    description: [
      'This globe of Ithris is etched with the coastlines as they were before the Reddening and, over them, the routes by which every town was brought up to the ships.',
      'Beside each town is a small mark. The Institute took years to understand them: they are counts of lanterns carried out.',
    ],
    notes: 'Coastline noise from the transmitted terrain map; routes are partially extrapolated.',
    related: ['sr-0092', 'sr-0116', 'sr-0110'],
    seed: 121,
  },
  {
    id: 'sr-0128',
    catalog: 'SR-0128',
    name: 'The First Mirror of the Choir',
    ithran: 'choir',
    era: 'great-encoding',
    kind: 'lens',
    line: 'ca',
    integrity: 86,
    material: 'Resonant mirror, lattice-backed',
    dimensions: '⌀ 3.4 m',
    received: 'OST 2238.11.05 · Dish 64',
    summary: 'The first of the million mirrors that turned a library into a beam.',
    description: [
      'The Choir girdled the dark world Ennis with a lattice of mirrors, each backed with resonant crystal, all fed by the swollen light of Vael. Together they could shape a library into a single coherent beam.',
      'This is the first mirror, set on the pole of Ennis in 390 BE. It is the reason we can see them at all.',
    ],
    notes:
      'Mirror figure is coherent to λ/40 at 393 nm — the Ca II K line the Institute uses as the colour of the Encoding.',
    related: ['sr-0134', 'sr-0140', 'sr-0013'],
    seed: 128,
  },
  {
    id: 'sr-0134',
    catalog: 'SR-0134',
    name: 'The Reading Crown',
    ithran: 'read',
    era: 'great-encoding',
    kind: 'instrument',
    line: 'ca',
    integrity: 61,
    material: 'Nested rings, crystal-lined',
    dimensions: '⌀ 28 cm',
    received: 'OST 2256.02.14 · Dish 50',
    summary: 'Worn by each Ithra who chose to be read into the Choir.',
    description: [
      'To be read into the Choir, an Ithra wore this crown of nested rings for one night. It did not take their memories; it asked for them, one at a time, and recorded only what was given.',
      'Almost every Ithra consented. The crown was worn by eleven million of them in the last seventy turns before the Encoding.',
    ],
    notes:
      'The ring tilts encode the order in which memories were requested: earliest first, as the Accord of Dusk required.',
    related: ['sr-0073', 'sr-0128', 'sr-0140'],
    seed: 134,
  },
  {
    id: 'sr-0140',
    catalog: 'SR-0140',
    name: 'The Last Voice',
    ithran: 'here',
    era: 'great-encoding',
    kind: 'bell',
    line: 'ca',
    integrity: 99,
    material: 'Resonant crystal',
    dimensions: '52 × 44 cm',
    received: 'OST 2236.03.14 · Dish 01',
    summary: 'The crystal that holds the final voices recorded before the Choir sang alone.',
    description: [
      'In the final turn, the last Ithra gathered on Ennis and spoke into a single crystal, shaped like the Singing Stone that had begun the Resonance thirty-seven thousand turns before.',
      'The Last Voice is carried in every cycle of the carrier. It was part of the very first thing the Halden Deep Array ever received, on the night of 14 March 2236. The Institute did not know, then, what it was listening to.',
    ],
    notes:
      'Integrity 99%: the Ithra repeated it more than any other object. The Institute has chosen not to publish a full translation; see Transmission Zero.',
    related: ['sr-0044', 'sr-0116', 'sr-0128'],
    seed: 140,
  },
];

export const relicById = (id: string): Relic | undefined => relics.find((r) => r.id === id);

export const relicsByEra = (eraId: string): Relic[] => relics.filter((r) => r.era === eraId);

export const RELIC_KIND_LABELS: Record<RelicKind, string> = {
  vessel: 'Vessel',
  lantern: 'Lantern',
  bell: 'Resonator',
  spire: 'Spire',
  lens: 'Lens & mirror',
  ring: 'Ring',
  lattice: 'Crystal',
  seed: 'Living thing',
  tablet: 'Inscription',
  map: 'Globe',
  instrument: 'Instrument',
  mask: 'Mask',
};

/** Relics featured on Arrival. */
export const FEATURED_RELICS = ['sr-0021', 'sr-0073', 'sr-0140'] as const;
